# Generated by Django 5.2 on 2025-05-04 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationintake',
            name='user',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='instructions',
            field=models.TextField(),
        ),
    ]
